services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    images: ghcr.io/cleign1/backend-golang-server-app:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    env_file: ".env"
    volumes:
      - ./buat-maen2-aja-9223ad2c5ec3_private_key_n8n_skripsi.json:/root/buat-maen2-aja-9223ad2c5ec3_private_key_n8n_skripsi.json:ro
    networks:
      - backend

networks:
  backend:
